name: quick_start_express CI

on:
    push:
        branches: ["main"]
    pull_request:
        branches: ["main"]
    workflow_dispatch:

jobs:
    run_tests:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout the repository.
              uses: actions/checkout@v4

            - name: Use Node.js LTS.
              uses: actions/setup-node@v4
              with:
                  node-version: "22.x"

            - name: Install Dependencies.
              run: npm i

            - name: Run code formatting Prettier tests.
              run: npm run test:format

            - name: Run Jest tests.
              run: npm run test
